/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ATable: typeof import('ant-design-vue/es')['Table']
    BoardTable: typeof import('./src/components/boardTable.vue')['default']
    Btn: typeof import('./src/components/common/btn.vue')['default']
    CabinetTable: typeof import('./src/components/cabinetTable.vue')['default']
    DropDownBtn: typeof import('./src/components/common/DropDownBtn.vue')['default']
    FloatBtnGroup: typeof import('./src/components/floatBtnGroup.vue')['default']
    HomeHeader: typeof import('./src/components/homeHeader.vue')['default']
    HomeMain: typeof import('./src/components/homeMain.vue')['default']
    MessageTip: typeof import('./src/components/messageTip.vue')['default']
    NavHeader: typeof import('./src/components/common/navHeader.vue')['default']
    PlankDetailHeader: typeof import('./src/components/plankDetail/plankDetailHeader.vue')['default']
    PlankHeader: typeof import('./src/components/plankDetail/plankHeader.vue')['default']
    PlankMain: typeof import('./src/components/plankDetail/plankMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selfbtn: typeof import('./src/components/common/selfbtn.vue')['default']
    SelfBtn: typeof import('./src/components/common/selfBtn.vue')['default']
    ThreejsScene: typeof import('./src/components/threejsScene.vue')['default']
    ThreeJsScene: typeof import('./src/components/plankDetail/threeJsScene.vue')['default']
  }
}
